"""p3_durable_state_tables

Revision ID: a3c69850b278
Revises: 16017dbdab8a
Create Date: 2026-06-03 18:25:37.285270
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

revision = 'a3c69850b278'
down_revision = '16017dbdab8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_export_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('export_types', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('download_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('checksum_manifest', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('error_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_export_jobs_status'), 'compliance_export_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_compliance_export_jobs_tenant_id'), 'compliance_export_jobs', ['tenant_id'], unique=False)
    op.create_table('cost_budgets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monthly_usd_cap', sa.Float(), nullable=False),
    sa.Column('alert_threshold_pct', sa.Float(), nullable=False),
    sa.Column('month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'month', name='uq_cost_budget_tenant_month')
    )
    op.create_index(op.f('ix_cost_budgets_month'), 'cost_budgets', ['month'], unique=False)
    op.create_index(op.f('ix_cost_budgets_tenant_id'), 'cost_budgets', ['tenant_id'], unique=False)
    op.create_table('cost_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_events_month'), 'cost_events', ['month'], unique=False)
    op.create_index(op.f('ix_cost_events_tenant_id'), 'cost_events', ['tenant_id'], unique=False)
    op.create_index('ix_cost_tenant_month', 'cost_events', ['tenant_id', 'month'], unique=False)
    op.create_table('sso_configs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idp_entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idp_sso_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idp_x509_cert', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_id_format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attribute_mapping', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', name='uq_sso_tenant')
    )
    op.create_index(op.f('ix_sso_configs_tenant_id'), 'sso_configs', ['tenant_id'], unique=True)
    op.create_table('experiments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dataset_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evaluator_ids', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['golden_datasets.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exp_tenant_created', 'experiments', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_experiments_dataset_id'), 'experiments', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_experiments_name'), 'experiments', ['name'], unique=False)
    op.create_index(op.f('ix_experiments_tenant_id'), 'experiments', ['tenant_id'], unique=False)
    op.create_table('experiment_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experiment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aggregate_score', sa.Float(), nullable=True),
    sa.Column('verdict_summary', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('ab_baseline_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ab_candidate_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ab_winner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ab_delta_score', sa.Float(), nullable=True),
    sa.Column('ab_cohens_d', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_runs_experiment_id'), 'experiment_runs', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_runs_status'), 'experiment_runs', ['status'], unique=False)
    op.create_index(op.f('ix_experiment_runs_tenant_id'), 'experiment_runs', ['tenant_id'], unique=False)
    op.create_index('ix_exprun_exp_created', 'experiment_runs', ['experiment_id', 'created_at'], unique=False)
    op.create_table('experiment_item_results',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('example_index', sa.Integer(), nullable=False),
    sa.Column('request_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verdicts', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('aggregate_score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_item_results_run_id'), 'experiment_item_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_experiment_item_results_tenant_id'), 'experiment_item_results', ['tenant_id'], unique=False)
    op.create_index('ix_expitem_run', 'experiment_item_results', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expitem_run', table_name='experiment_item_results')
    op.drop_index(op.f('ix_experiment_item_results_tenant_id'), table_name='experiment_item_results')
    op.drop_index(op.f('ix_experiment_item_results_run_id'), table_name='experiment_item_results')
    op.drop_table('experiment_item_results')
    op.drop_index('ix_exprun_exp_created', table_name='experiment_runs')
    op.drop_index(op.f('ix_experiment_runs_tenant_id'), table_name='experiment_runs')
    op.drop_index(op.f('ix_experiment_runs_status'), table_name='experiment_runs')
    op.drop_index(op.f('ix_experiment_runs_experiment_id'), table_name='experiment_runs')
    op.drop_table('experiment_runs')
    op.drop_index(op.f('ix_experiments_tenant_id'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_name'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_dataset_id'), table_name='experiments')
    op.drop_index('ix_exp_tenant_created', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_sso_configs_tenant_id'), table_name='sso_configs')
    op.drop_table('sso_configs')
    op.drop_index('ix_cost_tenant_month', table_name='cost_events')
    op.drop_index(op.f('ix_cost_events_tenant_id'), table_name='cost_events')
    op.drop_index(op.f('ix_cost_events_month'), table_name='cost_events')
    op.drop_table('cost_events')
    op.drop_index(op.f('ix_cost_budgets_tenant_id'), table_name='cost_budgets')
    op.drop_index(op.f('ix_cost_budgets_month'), table_name='cost_budgets')
    op.drop_table('cost_budgets')
    op.drop_index(op.f('ix_compliance_export_jobs_tenant_id'), table_name='compliance_export_jobs')
    op.drop_index(op.f('ix_compliance_export_jobs_status'), table_name='compliance_export_jobs')
    op.drop_table('compliance_export_jobs')
    # ### end Alembic commands ###
