"""initial schema

Revision ID: d8103754361c
Revises: 
Create Date: 2026-06-01 13:21:39.041459
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

revision = 'd8103754361c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sa.Enum('LOG', 'WEBHOOK', 'SLACK', name='alertchannel'), nullable=True),
    sa.Column('context', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_tenant_created', 'alerts', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'OPERATOR', 'VIEWER', name='role'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('gate_decisions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('candidate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('policy_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('aggregate_score', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('category_scores', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('baseline_deltas', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('regressions', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trace_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decision_tenant_created', 'gate_decisions', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_gate_decisions_candidate'), 'gate_decisions', ['candidate'], unique=False)
    op.create_index(op.f('ix_gate_decisions_created_at'), 'gate_decisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_gate_decisions_passed'), 'gate_decisions', ['passed'], unique=False)
    op.create_index(op.f('ix_gate_decisions_tenant_id'), 'gate_decisions', ['tenant_id'], unique=False)
    op.create_table('gate_policies',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('fail_on_any_blocking', sa.Boolean(), nullable=False),
    sa.Column('evaluator_policies', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', 'version', name='uq_policy_name_ver')
    )
    op.create_index(op.f('ix_gate_policies_name'), 'gate_policies', ['name'], unique=False)
    op.create_index(op.f('ix_gate_policies_tenant_id'), 'gate_policies', ['tenant_id'], unique=False)
    op.create_table('golden_datasets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('examples', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_golden_name')
    )
    op.create_index(op.f('ix_golden_datasets_name'), 'golden_datasets', ['name'], unique=False)
    op.create_index(op.f('ix_golden_datasets_tenant_id'), 'golden_datasets', ['tenant_id'], unique=False)
    op.create_table('traces',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('grounded_facts', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_created_at'), 'traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_traces_intent'), 'traces', ['intent'], unique=False)
    op.create_index('ix_traces_tenant_created', 'traces', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_traces_tenant_id'), 'traces', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'OPERATOR', 'VIEWER', name='role'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evaluator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('findings', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eval_tenant_evaluator', 'evaluations', ['tenant_id', 'evaluator'], unique=False)
    op.create_index(op.f('ix_evaluations_created_at'), 'evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluations_evaluator'), 'evaluations', ['evaluator'], unique=False)
    op.create_index(op.f('ix_evaluations_tenant_id'), 'evaluations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_evaluations_trace_id'), 'evaluations', ['trace_id'], unique=False)
    op.create_index(op.f('ix_evaluations_verdict'), 'evaluations', ['verdict'], unique=False)
    op.create_table('spans',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(sqlite.JSON(), 'sqlite'), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spans_tenant_id'), 'spans', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_spans_trace_id'), 'spans', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spans_trace_id'), table_name='spans')
    op.drop_index(op.f('ix_spans_tenant_id'), table_name='spans')
    op.drop_table('spans')
    op.drop_index(op.f('ix_evaluations_verdict'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_trace_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_tenant_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_evaluator'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_created_at'), table_name='evaluations')
    op.drop_index('ix_eval_tenant_evaluator', table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_traces_tenant_id'), table_name='traces')
    op.drop_index('ix_traces_tenant_created', table_name='traces')
    op.drop_index(op.f('ix_traces_intent'), table_name='traces')
    op.drop_index(op.f('ix_traces_created_at'), table_name='traces')
    op.drop_table('traces')
    op.drop_index(op.f('ix_golden_datasets_tenant_id'), table_name='golden_datasets')
    op.drop_index(op.f('ix_golden_datasets_name'), table_name='golden_datasets')
    op.drop_table('golden_datasets')
    op.drop_index(op.f('ix_gate_policies_tenant_id'), table_name='gate_policies')
    op.drop_index(op.f('ix_gate_policies_name'), table_name='gate_policies')
    op.drop_table('gate_policies')
    op.drop_index(op.f('ix_gate_decisions_tenant_id'), table_name='gate_decisions')
    op.drop_index(op.f('ix_gate_decisions_passed'), table_name='gate_decisions')
    op.drop_index(op.f('ix_gate_decisions_created_at'), table_name='gate_decisions')
    op.drop_index(op.f('ix_gate_decisions_candidate'), table_name='gate_decisions')
    op.drop_index('ix_decision_tenant_created', table_name='gate_decisions')
    op.drop_table('gate_decisions')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index('ix_alert_tenant_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
